name: Push to another repo

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger on

jobs:
  push_code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'chathushkaayash'
        git config --global user.email 'chathushkaayash@gmail.com'

    - name: Add target repo as a remote
      run: |
        ls -a
        git remote add target https://github.com/chathushkaayash/Smart-Shopper-Frontend.git

      env:
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}

    - name: Push to target repo
      run: |
        git push -u target master --force
      env:
        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
