
name: Automatic Push to Another Repository

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'chathushkaayash'
          destination-repository-name: 'Smart-Shopper-Frontend'
          user-email: chathushkaayash@gmail.com
          commit-message: See ORIGIN_COMMIT 
          target-branch: master
      - name: Test get variable exported by push-to-another-repository
        run: echo gbj